Repository dnd-side-project/dnd-11th-10-backend, pull requests merged in 2024-08, with the labels that each got.

#9 Synchronize develop Branch
  .github/workflows/backend-pr-test.yml
  .github/workflows/backend-publish.yml
Labels: build, ci

#16 Add Docker File
  Dockerfile
Labels: build

#17 Synchronize main Branch
  Dockerfile
Labels: build, ci

#19 Fix Publish Script
  .github/workflows/backend-publish.yml
Labels: bug, hotfix

#21 Synchronize develop Branch
  .github/workflows/backend-publish.yml
Labels: build, ci

#22 Add Dictionary Lookup Function
  src/main/java/com/dnd/spaced/domain/account/domain/repository/QuerydslAccountRepository.java
  src/main/java/com/dnd/spaced/domain/word/application/WordService.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/WordServiceMapper.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/request/WordConditionInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/DetailWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/InputWordCandidateDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/event/ViewCountCalculateEventListener.java
  src/main/java/com/dnd/spaced/domain/word/application/event/dto/request/FoundWordInfoEvent.java
  src/main/java/com/dnd/spaced/domain/word/application/exception/ForbiddenBookmarkException.java
  src/main/java/com/dnd/spaced/domain/word/application/exception/WordNotFoundException.java
  src/main/java/com/dnd/spaced/domain/word/domain/Bookmark.java
  src/main/java/com/dnd/spaced/domain/word/domain/Category.java
  src/main/java/com/dnd/spaced/domain/word/domain/Pronunciation.java
  src/main/java/com/dnd/spaced/domain/word/domain/Word.java
  src/main/java/com/dnd/spaced/domain/word/domain/exception/InvalidCategoryException.java
  src/main/java/com/dnd/spaced/domain/word/domain/exception/InvalidExampleException.java
  src/main/java/com/dnd/spaced/domain/word/domain/exception/InvalidMeaningException.java
  src/main/java/com/dnd/spaced/domain/word/domain/exception/InvalidNameException.java
  src/main/java/com/dnd/spaced/domain/word/domain/exception/InvalidPronunciationException.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/BookmarkCrudRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/BookmarkRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslBookmarkRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/WordRepositoryMapper.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/request/WordConditionDto.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordCandidateDto.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordInfoWithBookmarkDto.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/exception/UnsupportedCommentSortConditionException.java
  src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/WordControllerMapper.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/MultipleWordConditionRequest.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/InputWordCandidateResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordInfoResponse.java
  src/main/java/com/dnd/spaced/global/config/AppConfig.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
  src/main/java/com/dnd/spaced/global/repository/OrderByNull.java
  src/main/java/com/dnd/spaced/global/resolver/word/WordSortCondition.java
  src/main/java/com/dnd/spaced/global/resolver/word/WordSortConditionArgumentResolver.java
Labels: feature

#27 Add Report Function
  src/main/java/com/dnd/spaced/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/dnd/spaced/domain/comment/domain/repository/QuerydslCommentRepository.java
  src/main/java/com/dnd/spaced/domain/report/application/ReportService.java
  src/main/java/com/dnd/spaced/domain/report/application/ReportServiceMapper.java
  src/main/java/com/dnd/spaced/domain/report/application/dto/request/ReportInfoDto.java
  src/main/java/com/dnd/spaced/domain/report/application/exception/ForbiddenReportAccountException.java
  src/main/java/com/dnd/spaced/domain/report/application/exception/ReportedCommentNotFoundException.java
  src/main/java/com/dnd/spaced/domain/report/domain/Reason.java
  src/main/java/com/dnd/spaced/domain/report/domain/Report.java
  src/main/java/com/dnd/spaced/domain/report/domain/exception/InvalidReasonNameException.java
  src/main/java/com/dnd/spaced/domain/report/domain/repository/QuerydslReportRepository.java
  src/main/java/com/dnd/spaced/domain/report/domain/repository/ReportCrudRepository.java
  src/main/java/com/dnd/spaced/domain/report/domain/repository/ReportRepository.java
  src/main/java/com/dnd/spaced/domain/report/presentation/ReportController.java
  src/main/java/com/dnd/spaced/domain/report/presentation/dto/request/ReportInfoRequest.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
  src/main/java/com/dnd/spaced/global/exception/GlobalControllerAdvice.java
Labels: feature

#34 Add Local Image Lookup Function
  src/main/java/com/dnd/spaced/domain/image/application/LocalImageService.java
  src/main/java/com/dnd/spaced/domain/image/presentation/LocalImageController.java
  src/main/java/com/dnd/spaced/global/config/AppConfig.java
  src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
  src/main/java/com/dnd/spaced/global/config/properties/ImageStorePathProperties.java
  src/main/java/com/dnd/spaced/global/exception/GlobalControllerAdvice.java
  src/main/java/com/dnd/spaced/global/interceptor/AuthInterceptor.java
  src/main/resources/application-local.yml
Labels: feature

#36 Add Word Test Api With Mock data
  src/main/java/com/dnd/spaced/domain/learning/LeaningController.java
  src/main/java/com/dnd/spaced/domain/learning/dto/request/SolveTestRequest.java
  src/main/java/com/dnd/spaced/domain/learning/dto/response/TestExplanationResponse.java
  src/main/java/com/dnd/spaced/domain/learning/dto/response/TestProblemResponse.java
  src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
Labels: feature

#31 Add Word Search List Lookup Function
  src/main/java/com/dnd/spaced/domain/word/application/WordService.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/WordServiceMapper.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordSearchDto.java
  src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/WordSearchRequest.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordSearchInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordSearchResponse.java
Labels: feature

#37 Fix Account Career Info Function
  src/main/java/com/dnd/spaced/domain/account/domain/Account.java
  src/main/java/com/dnd/spaced/domain/account/domain/CareerInfo.java
  src/main/java/com/dnd/spaced/domain/account/domain/Company.java
  src/main/java/com/dnd/spaced/domain/account/domain/Experience.java
  src/main/java/com/dnd/spaced/domain/account/domain/exception/InvalidCompanyException.java
  src/main/java/com/dnd/spaced/domain/account/domain/exception/InvalidExperienceException.java
  src/main/java/com/dnd/spaced/domain/auth/application/AuthService.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/AuthController.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/dto/request/CareerInfoRequest.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/dto/request/InitProfileRequest.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
Labels: fix

#39 Add Bookmark Function
  src/main/java/com/dnd/spaced/domain/bookmark/application/BookmarkService.java
  src/main/java/com/dnd/spaced/domain/bookmark/application/dto/BookmarkServiceMapper.java
  src/main/java/com/dnd/spaced/domain/bookmark/application/dto/request/BookmarkConditionInfoDto.java
  src/main/java/com/dnd/spaced/domain/bookmark/application/dto/response/BookmarkWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/bookmark/application/exception/BookmarkWordNotFoundException.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/Bookmark.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/BookmarkCrudRepository.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/QuerydslBookmarkRepository.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/BookmarkRepositoryMapper.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/request/BookmarkConditionDto.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/response/BookmarkWordDto.java
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/BookmarkControllerMapper.java
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/request/BookmarkConditionRequest.java
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java
  src/main/java/com/dnd/spaced/domain/word/application/WordService.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/BookmarkRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslBookmarkRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
Labels: feature, refactor

#41 Change Word Test Response
  src/main/java/com/dnd/spaced/domain/learning/LeaningController.java
  src/main/java/com/dnd/spaced/domain/learning/dto/response/TestExplanationResponse.java
  src/main/java/com/dnd/spaced/domain/learning/dto/response/TestProblemResponse.java
Labels: refactor

#43 Fix Publish Script
  .github/workflows/backend-publish.yml
Labels: feature, build

#46 Synchronize develop Branch
  .github/workflows/backend-publish.yml
Labels: build, ci

#50 Change Word API
  src/main/java/com/dnd/spaced/domain/bookmark/application/dto/response/BookmarkWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java
  src/main/java/com/dnd/spaced/domain/comment/application/dto/response/MultiplePopularCommentInfoDto.java
  src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/MultiplePopularCommentInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/application/WordService.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/WordServiceMapper.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/request/SearchWordConditionInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/request/WordConditionInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/DetailWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/WordSearchInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/domain/Pronunciation.java
  src/main/java/com/dnd/spaced/domain/word/domain/Word.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/WordRepositoryMapper.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/request/SearchWordConditionDto.java
  src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/WordControllerMapper.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/WordSearchRequest.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleSearchWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordSearchInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordSearchResponse.java
  src/main/java/com/dnd/spaced/global/config/AppConfig.java
  src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
  src/main/java/com/dnd/spaced/global/resolver/word/SearchWordSortCondition.java
  src/main/java/com/dnd/spaced/global/resolver/word/SearchWordSortConditionArgumentResolver.java
Labels: fix

#56 Add Popular Word Lookup Function
  src/main/java/com/dnd/spaced/domain/word/application/WordService.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/WordServiceMapper.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/PopularWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/event/PopularWordViewCountCalculateEventListener.java
  src/main/java/com/dnd/spaced/domain/word/application/event/ViewCountCalculateEventListener.java
  src/main/java/com/dnd/spaced/domain/word/application/event/dto/request/FoundWordPopularViewCountEvent.java
  src/main/java/com/dnd/spaced/domain/word/application/event/dto/request/FoundWordViewCountEvent.java
  src/main/java/com/dnd/spaced/domain/word/application/exception/PopularWordScheduleNotFoundException.java
  src/main/java/com/dnd/spaced/domain/word/application/schedule/PopularWordScheduler.java
  src/main/java/com/dnd/spaced/domain/word/domain/PopularWordMetadata.java
  src/main/java/com/dnd/spaced/domain/word/domain/PopularWordSchedule.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/PopularWordMetadataCrudRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/PopularWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/PopularWordScheduleCrudRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslPopularWordMetadataRepository.java
  src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/WordControllerMapper.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/PopularWordResponse.java
  src/main/java/com/dnd/spaced/global/config/AppConfig.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
  src/main/java/com/dnd/spaced/global/resolver/word/PopularWordSortCondition.java
  src/main/java/com/dnd/spaced/global/resolver/word/PopularWordSortConditionArgumentResolver.java
Labels: feature

#58 Add Word API Documentation
  src/main/java/com/dnd/spaced/domain/word/presentation/SwaggerWordController.java
  src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/MultipleWordConditionRequest.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/WordSearchRequest.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/InputWordCandidateResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleSearchWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/PopularWordResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordSearchInfoResponse.java
Labels: docs

#60 Add Auth API Documentation
  src/main/java/com/dnd/spaced/domain/account/domain/Company.java
  src/main/java/com/dnd/spaced/domain/account/domain/JobGroup.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/AuthController.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/SwaggerAuthController.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/dto/request/CareerInfoRequest.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/dto/response/TokenResponse.java
  src/main/java/com/dnd/spaced/global/config/DocsConfig.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
Labels: docs

#64 Add Bookmark API Documentation
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/BookmarkController.java
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/SwaggerBookmarkController.java
  src/main/java/com/dnd/spaced/global/config/AppConfig.java
  src/main/java/com/dnd/spaced/global/resolver/bookmark/BookmarkSortCondition.java
  src/main/java/com/dnd/spaced/global/resolver/bookmark/BookmarkSortConditionArgumentResolver.java
Labels: docs

#68 Add Account JobGroup Element
  src/main/java/com/dnd/spaced/domain/account/domain/JobGroup.java
  src/main/java/com/dnd/spaced/domain/auth/presentation/dto/request/CareerInfoRequest.java
Labels: docs, refactor

#70 Fix Word Bookmark Logic
  src/main/java/com/dnd/spaced/domain/bookmark/application/BookmarkService.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/DetailWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/domain/Word.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordInfoWithBookmarkDto.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java
Labels: fix

#75 Add Admin Function Related To Word
  src/main/java/com/dnd/spaced/domain/admin/application/AdminService.java
  src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java
  src/main/java/com/dnd/spaced/domain/admin/application/dto/request/AdminWordRequestDto.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/AdminController.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/AdminWordResponse.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/WordCrudRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java
  src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
Labels: feature

#71 Add Word Quiz Function
  src/main/java/com/dnd/spaced/domain/learning/LeaningController.java
  src/main/java/com/dnd/spaced/domain/quiz/application/QuizService.java
  src/main/java/com/dnd/spaced/domain/quiz/application/dto/QuizServiceMapper.java
  src/main/java/com/dnd/spaced/domain/quiz/application/dto/request/QuizRequestDto.java
  src/main/java/com/dnd/spaced/domain/quiz/application/dto/response/QuizResponseDto.java
  src/main/java/com/dnd/spaced/domain/quiz/application/exception/InvalidOptionException.java
  src/main/java/com/dnd/spaced/domain/quiz/application/exception/NotEnoughQuestionsException.java
  src/main/java/com/dnd/spaced/domain/quiz/application/exception/QuizNotFoundException.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/Category.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/Quiz.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/QuizOption.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/QuizQuestion.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/QuizResult.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuerydslQuizRepository.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuizCrudRepository.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuizRepository.java
  src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuizResultRepository.java
  src/main/java/com/dnd/spaced/domain/quiz/presentation/QuizController.java
  src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/QuizControllerMapper.java
  src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/request/QuizRequest.java
  src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/response/QuizResponse.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
Labels: feature

#76 Add Admin Function Related To Reported Comment
  src/main/java/com/dnd/spaced/domain/admin/application/AdminService.java
  src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java
  src/main/java/com/dnd/spaced/domain/admin/application/dto/response/ReportInfoDto.java
  src/main/java/com/dnd/spaced/domain/admin/application/exception/ReportNotFoundException.java
  src/main/java/com/dnd/spaced/domain/admin/domain/AdminReportComment.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/AdminController.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/dto/AdminControllerMapper.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/ReportListResponse.java
  src/main/java/com/dnd/spaced/domain/report/domain/Report.java
  src/main/java/com/dnd/spaced/domain/report/domain/repository/QuerydslReportRepository.java
  src/main/java/com/dnd/spaced/domain/report/domain/repository/ReportCrudRepository.java
  src/main/java/com/dnd/spaced/domain/report/domain/repository/ReportRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/Word.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
Labels: feature

#78 Add Word Quiz Documentation
  src/main/java/com/dnd/spaced/domain/quiz/presentation/QuizController.java
  src/main/java/com/dnd/spaced/domain/quiz/presentation/SwaggerQuizController.java
  src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/request/QuizRequest.java
  src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/response/QuizResponse.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
Labels: docs

#81 Change Popular Comment Response Format
  src/main/java/com/dnd/spaced/domain/comment/application/dto/response/MultiplePopularCommentInfoDto.java
  src/main/java/com/dnd/spaced/domain/comment/domain/repository/QuerydslCommentRepository.java
  src/main/java/com/dnd/spaced/domain/comment/domain/repository/dto/response/PopularCommentInfoDto.java
  src/main/java/com/dnd/spaced/domain/comment/presentation/dto/CommentControllerMapper.java
  src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/MultiplePopularCommentInfoResponse.java
Labels: refactor

#85 Fix Publish Script
  .github/workflows/backend-publish.yml
Labels: fix, build

#87 Refactor Docker File
  Dockerfile
Labels: build

#89 Change Word Response Format
  src/main/java/com/dnd/spaced/domain/word/application/WordService.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/WordServiceMapper.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/InputWordCandidateDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/WordSearchInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/WordRepositoryMapper.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordCandidateDto.java
  src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/WordControllerMapper.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/InputWordCandidateResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleSearchWordInfoResponse.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleWordInfoResponse.java
Labels: fix, refactor

#91 Synchronize develop Branch
  .github/workflows/backend-publish.yml
  Dockerfile
Labels: ci

#93 Fix Word Domain Format
  src/main/java/com/dnd/spaced/domain/admin/application/AdminService.java
  src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/AdminController.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/SwaggerAdminController.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/dto/request/AddWordExampleRequest.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/dto/request/UpdateWordExampleRequest.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/AdminWordResponse.java
  src/main/java/com/dnd/spaced/domain/bookmark/application/dto/response/BookmarkWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/QuerydslBookmarkRepository.java
  src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/response/BookmarkWordDto.java
  src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/DetailWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java
  src/main/java/com/dnd/spaced/domain/word/domain/Word.java
  src/main/java/com/dnd/spaced/domain/word/domain/WordExample.java
  src/main/java/com/dnd/spaced/domain/word/domain/exception/WordExampleNotFoundException.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
  src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordInfoWithBookmarkDto.java
  src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionCode.java
  src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
Labels: fix, feature, refactor

#95 Add Admin Permissions Handling
  src/main/java/com/dnd/spaced/domain/admin/presentation/AdminController.java
  src/main/java/com/dnd/spaced/domain/admin/presentation/SwaggerAdminController.java
  src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
Labels: fix

#98 Fix logback setting
  src/main/resources/application.yml
Labels: hotfix
